fullnameOverride: opentelemetry-logs
mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  kubernetesAttributes:
    enabled: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  enabled: true
  type: ClusterIP

ports:
  otlp:
    enabled: false
  otlp-http:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
      interval: 30s

config:
  exporters:
    debug: null
    otlphttp/loki:
      endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
  processors:
    resource/logs:
      attributes:
        - action: upsert
          key: namespace
          from_attribute: k8s.namespace.name
        - action: upsert
          key: container
          from_attribute: k8s.container.name
        - action: upsert
          key: service.name
          from_attribute: k8s.container.name
        - action: upsert
          key: service.namespace
          from_attribute: k8s.namespace.name
  receivers:
    jaeger: null
    otlp: null
    prometheus: null
    zipkin: null
  service:
    pipelines:
      logs:
        receivers:
          - filelog
        processors:
          - memory_limiter
          - k8sattributes
          - resource/logs
          - batch
        exporters:
          - otlphttp/loki
      metrics: null
      traces: null

tolerations:
  - operator: Exists
