apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 9.1.0
      helm:
        valueFiles:
          - $values/platform/falco/values.yaml
          - $values/envs/prod/aws/ap-southeast-1/platform/falco/values.yaml
    - repoURL: https://github.com/nguyentin05/nexus-gitops.git
      targetRevision: production
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
