replicaCount: 1

image:
  repository: ghcr.io/nguyentin05/nexus-profile-service
  tag: dev
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

serviceMonitor:
  enabled: false
  path: /metrics
  interval: 30s

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}


env:
  - name: AWS_REGION
    value: ap-southeast-1

envFrom:
  - secretRef:
      name: profile-service-secrets
      optional: true
