replicaCount: 1
image:
  repository: 065320271480.dkr.ecr.ap-southeast-1.amazonaws.com/nexus-profile-service
  tag: v0.1.4
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
nodeSelector:
  role: system
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
env:
  - name: AWS_REGION
    value: ap-southeast-1
envFrom:
  - secretRef:
      name: profile-service-secrets
      optional: true
serviceAccount:
  create: true
  name: ""
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::065320271480:role/dev-profile-service-irsa
