replicaCount: 2
image:
  repository: 065320271480.dkr.ecr.ap-southeast-1.amazonaws.com/nexus-profile-service
  tag: v0.2.5
  pullPolicy: IfNotPresent
serviceMonitor:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
nodeSelector:
  intent: apps
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::065320271480:role/prod-profile-service-irsa
