fullnameOverride: monitoring

systemTolerations: &systemTolerations
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule

alertmanager:
  enabled: true
  alertmanagerSpec:
    retention: 24h
    tolerations: *systemTolerations
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: prom-operator
  service:
    type: ClusterIP
  ingress:
    enabled: false
  persistence:
    enabled: false
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
  tolerations: *systemTolerations
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 6h
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    tolerations: *systemTolerations
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

prometheusOperator:
  enabled: true
  tolerations: *systemTolerations
  admissionWebhooks:
    patch:
      tolerations: *systemTolerations
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: true

coreDns:
  enabled: true

kube-state-metrics:
  tolerations: *systemTolerations
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  enabled: false

prometheus-node-exporter:
  tolerations:
    - operator: Exists
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
