systemNodeSelector: &systemNodeSelector
  kubernetes.io/os: linux
  role: system

systemTolerations: &systemTolerations
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule

crds:
  migration:
    nodeSelector: *systemNodeSelector
    tolerations: *systemTolerations

admissionController:
  nodeSelector: *systemNodeSelector
  tolerations: *systemTolerations

backgroundController:
  nodeSelector: *systemNodeSelector
  tolerations: *systemTolerations

cleanupController:
  nodeSelector: *systemNodeSelector
  tolerations: *systemTolerations

reportsController:
  nodeSelector: *systemNodeSelector
  tolerations: *systemTolerations
