replicaCount: 2

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::065320271480:role/prod-aws-load-balancer-controller-irsa

clusterName: prod-capstone-eks
region: ap-southeast-1

vpcTags:
  Name: prod-vpc
  Project: capstone
