apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "monitoring-agent.fullname" . }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "monitoring-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monitoring-agent.fullname" . }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "monitoring-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "monitoring-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "monitoring-agent.fullname" . }}
