{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "auth-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    canary:
      stableService: {{ include "auth-service.fullname" . }}
      canaryService: {{ include "auth-service.fullname" . }}-canary
      maxSurge: 1
      maxUnavailable: 0
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: auth-service
            namespace: {{ .Release.Namespace }}
      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - analysis:
            templates:
              - templateName: {{ include "auth-service.fullname" . }}-slo
            args:
              - name: service-name
                value: {{ include "auth-service.fullname" . }}-canary
        - setWeight: 50
        - pause:
            duration: 5m
        - analysis:
            templates:
              - templateName: {{ include "auth-service.fullname" . }}-slo
            args:
              - name: service-name
                value: {{ include "auth-service.fullname" . }}-canary
{{ include "auth-service.podTemplate" . | nindent 2 }}
{{- end }}
