replicaCount: 1

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::863547508328:role/dev-aws-load-balancer-controller-irsa

clusterName: dev-major-eks
region: ap-southeast-1

vpcTags:
  Project: major
  Environment: dev
