global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false
  replicas: 1
  authPath: auth/kubernetes

server:
  serviceAccount:
    create: true
    name: vault
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::065320271480:role/dev-vault-20260708041611768000000018
    serviceDiscovery:
      enabled: true

  authDelegator:
    enabled: true

  nodeSelector:
    role: system
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: gp2

  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable     = 1
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        seal "awskms" {
          region     = "ap-southeast-1"
          kms_key_id = "a0764fe0-71ae-43b1-a006-e3c88a91ec32"
        }

        service_registration "kubernetes" {}
