deployment:
  replicas: 1
  pod:
    nodeSelector:
      role: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule

certgen:
  job:
    nodeSelector:
      role: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
