replicaCount: 1

image:
  repository: ghcr.io/nguyentin05/nexus-monitoring-agent
  tag: dev
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

targetNamespace: apps

service:
  port: 8080

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s

config:
  mode: shadow
  awsRegion: ap-southeast-1
  bedrockModelId: global.amazon.nova-2-lite-v1:0
  prometheusUrl: http://monitoring-prometheus.monitoring.svc.cluster.local:9090
  lokiUrl: http://loki-gateway.monitoring.svc.cluster.local
  targetNamespace: apps
  watchedServices: auth-service,profile-service
  pollInterval: 1m
  incidentCooldown: 10m
  maxBedrockCallsPerHour: 10

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
