image:
  repository: 863547508328.dkr.ecr.ap-southeast-1.amazonaws.com/nexus-monitoring-agent
  tag: sha-45c840f9b5df1b1e5f68d1b196733be3424dfb9a
serviceAccount:
  name: nexus-monitoring-agent
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::863547508328:role/dev-monitoring-agent-irsa
config:
  mode: detect
nodeSelector:
  role: system
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
