image:
  repository: 863547508328.dkr.ecr.ap-southeast-1.amazonaws.com/nexus-monitoring-agent
  tag: sha-cc04eb9281e05cb9970a4f5c7cd9d920009c58b6
serviceAccount:
  name: nexus-monitoring-agent
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::863547508328:role/dev-monitoring-agent-irsa
config:
  mode: detect
nodeSelector:
  role: system
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
