serviceAccount:
  create: true
  name: aws-load-balancer-controller

nodeSelector:
  role: system

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule

enableServiceMutatorWebhook: false
