loki:
  limits_config:
    retention_period: 24h

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: storage
      emptyDir: {}
  extraVolumeMounts:
    - name: storage
      mountPath: /var/loki
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

gateway:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
