apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/nguyentin05/nexus-gitops.git
    targetRevision: main
    path: charts/profile-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
