fullnameOverride: promtail

config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

tolerations:
  - operator: Exists

readinessProbe:
  failureThreshold: 10
  timeoutSeconds: 5

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
