replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.27-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  role: system

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
