replicaCount: 1

image:
  repository: ghcr.io/nguyentin05/nexus-auth-service
  tag: dev
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
