apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: system-node-proxy
  namespace: apps
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: envoy-public-gateway
        type: ClusterIP
      envoyDeployment:
        pod:
          nodeSelector:
            role: system
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
              effect: NoSchedule
