apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: auth-service-db-creds
  namespace: apps
spec:
  path: /database/creds/auth-service
  method: GET
  resultType: Data
  provider:
    server: http://vault.vault.svc:8200
    auth:
      kubernetes:
        mountPath: kubernetes
        role: external-secrets
        serviceAccountRef:
          name: external-secrets
