admissionController:
  replicas: 1
  rbac:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::863547508328:role/dev-kyverno-image-verifier-irsa

backgroundController:
  replicas: 1
  rbac:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::863547508328:role/dev-kyverno-image-verifier-irsa

cleanupController:
  replicas: 1

reportsController:
  replicas: 1
  rbac:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::863547508328:role/dev-kyverno-image-verifier-irsa
