apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-config
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: api-gateway/config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-config
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: auth-service/config
