apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .DATABASE_ENDPOINT }}/{{ .DATABASE_NAME }}"
  dataFrom:
    - extract:
        key: auth-service/config
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: auth-service-db-creds
