apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: profile-service
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: profile-service-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .DATABASE_ENDPOINT }}/{{ .DATABASE_NAME }}?sslmode=require"
  dataFrom:
    - extract:
        key: profile-service/config
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: profile-service-db-creds
