apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: profile-service
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: profile-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: profile-service/config
